### ISSUE TITLE
obsolete use of linspace in screenshot

### ISSUE THREAD

**Issue by kookma** [mitmath/julia-mit#12]
**linspace**

In https://github.com/mitmath/julia-mit the Readme has example for plotting using PyPlot. I has the below code

`using PyPlot
x=linspace(0, 2pi, 1000)
y=sin(3x + 4cos(2x))
plot(x,y, color=red, linewidth=2.0, linestyle="--")
title("plot of an oscillatory function")
xlabel("the x axis")
`

But the Julia 1.5 does not support linspcae and this is confusing for newbies.

**Comment by stevengj** [comment]
Yes, I should update that screenshot.
